language: node_js
node_js:
- '10'
- '8'
- '6'
- '4'
deploy:
  provider: npm
  email: calidion@gmail.com

dist: xenial
env:
  - CXX=g++-6
addons:
  apt:
    packages:
      - build-essential
      - g++-6
      - make
      - libboost1.55-all-dev