language: node_js
sudo: required
node_js:
- '10'
- '8'
- '6'
- '4'
deploy:
  provider: npm
  email: calidion@gmail.com
dist: trusty
services:
  - docker
before_install:
  - docker pull ubuntu:16.04
addons:
  apt:
    packages:
      - build-essential
      - g++-6
      - make
      - libboost1.55-all-dev