language: node_js
node_js:
- '10'
- '8'
- '6'
- '4'
deploy:
  provider: npm
  email: calidion@gmail.com
env:
  - CXX=g++-5 CFLAGS=--std=c11
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libboost1.55-all-dev